dist: focal
language: perl
perl:
  - "5.30"
  - "5.24"
  - "5.12"
before_install:
  - sudo cpanm --notest Module::Build
install:
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cpanminus
    - gzip
    - lbzip2
    - libfile-which-perl
    - lz4
    - lzip
    - pbzip2
    - pigz
    - plzip
    - xz-utils
    - zstd
