dist: trusty
language: perl
perl:
  - "5.30"
  - "5.24"
  - "5.12"
before_install:
  - cpanm --notest Module::Build
install:
  - cpanm --quiet --installdeps --notest .
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gzip
    - lbzip2
    - lz4
    - lzip
    - pbzip2
    - pigz
    - plzip
    - xz-utils
    - zstd
